# Module: NumPy Assignments

## Lesson: NumPy

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [1]:
import numpy as np

In [ ]:
## 1. Create a NumPy array of shape (5, 5) filled with 
# random integers between 1 and 20. 

array = np.random.randint(1,21, size = (5,5))
print("Original array:")
print(array)

# Replace all the elements in the third column with 1.
array[:,2] = 1
print("Modified array:")
print(array)

Original array:
[[13  2  9 14 10]
 [12  8  3 20  1]
 [16  9  2  3 10]
 [12 18  8  3 13]
 [ 9 20  8 11  2]]
Modified array:
[[13  2  1 14 10]
 [12  8  1 20  1]
 [16  9  1  3 10]
 [12 18  1  3 13]
 [ 9 20  1 11  2]]


In [22]:
array  = np.random.randint(1,21, size=(5,5))
print(f"array: ")
print(array)

array[:,2] =1
print(f"Modified array:")
print(array)

array: 
[[ 7 19  2 13  4]
 [ 3  9 14 19  1]
 [ 9  7  6  2 17]
 [ 8  2 20 20 13]
 [ 1 13 11 12 12]]
Modified array:
[[ 7 19  1 13  4]
 [ 3  9  1 19  1]
 [ 9  7  1  2 17]
 [ 8  2  1 20 13]
 [ 1 13  1 12 12]]


In [ ]:
#2. Create a NumPy array of shape (4, 4) with values 
# from 1 to 16. 


array = np.arange(1,17).reshape((4,4))
print(array)

# Replace the diagonal elements with 0.
    # What is diagonal?
    # Positions affected:
    # (0,0), (1,1), (2,2), (3,3)

np.fill_diagonal(array,0)
print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [44]:
#1. Create a NumPy array of shape (6, 6) with values from 1 to 36. 


array = np.arange(1,37).reshape((6,6))
print("Original array:")
print(array)

# Extract the sub-array consisting of the 
# 3rd to 5th rows and 2nd to 4th columns.

sub_array = array[2:5,1:4]
print("Sub-array:")
print(sub_array)

Original array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sub-array:
[[14 15 16]
 [20 21 22]
 [26 27 28]]


In [58]:
## 2. Create a NumPy array of shape (5, 5) with random integers.
array = np.random.randint(1,10,size = (5,5))
print("array")
print(array)

# Extract the elements on the border.
# array[0:1,:] # first row
# array[-1:,:] # last row
# array[:,0:1] # first column
# array[:,-1:] # last column
border_elements = np.concatenate((array[0, :], array[-1, :], array[1:-1, 0], array[1:-1, -1]), axis=0)
print("Border elements:")
print(border_elements)



array
[[3 5 5 2 6]
 [4 2 9 5 2]
 [2 3 6 9 9]
 [2 7 8 4 8]
 [6 9 9 5 3]]
Border elements:
[3 5 5 2 6 6 9 9 5 3 4 2 2 2 9 8]
