# Numpy Library
numPy is a genral-purpose array- processing package. It provides  a high-preformance multidimensional array object. and tools for working with  these arrays. It is the fundamental package for scientific computing with Python.

# What is an Array
An array is a data structure that stores the values of same data type. in Python, this is the main difference between array and lists. While python lists can contain values corresponding to different data type, array in python can only contain values corresponding to same data type

In [1]:
## initially  lets import numpy
import numpy as np

In [3]:
my_list = [1,2,3,4,5]
arr = np.array(my_list)
arr

array([1, 2, 3, 4, 5])

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
print(arr)

[1 2 3 4 5]


In [6]:
arr.shape

(5,)

In [8]:
arr.reshape(2,2)

ValueError: cannot reshape array of size 5 into shape (2,2)

In [29]:
# multinested array
my_list1 = [1,2,3,4,5]
my_list2 = [2,3,4,5,6]
my_list3 = [9,7,6,8,9]

arr= np.array([my_list1,my_list2, my_list3 ])
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [11]:
arr.shape

(3, 5)

In [14]:
arr.reshape(5,3) # rechape is depends only the elements 

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [15]:
### chack the shape of the array
arr.shape

(3, 5)

# Indexing

In [24]:
## Accessing the array element
arr1 = np.array ([1,2,3,4,5,6,7,8,9])

In [25]:
arr1[4]

5

In [26]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
# multinested array
my_list1 = [1,2,3,4,7]
my_list2 = [2,3,6,5,6]
my_list3 = [9,7,6,8,9]

arr= np.array([my_list1,my_list2, my_list3 ])
arr

array([[1, 2, 3, 4, 7],
       [2, 3, 6, 5, 6],
       [9, 7, 6, 8, 9]])

In [39]:
arr

array([[1, 2, 3, 4, 7],
       [2, 3, 6, 5, 6],
       [9, 7, 6, 8, 9]])

In [40]:
arr1[0:6]

array([1, 2, 3, 4, 5, 6])

In [33]:
arr[1: , 3:]

array([[5, 6],
       [8, 9]])

In [41]:
arr[1:, 2:4]

array([[6, 5],
       [6, 8]])

In [42]:
arr[1:2, 1:4]

array([[3, 6, 5]])

In [43]:
arr= np.arange(0,10)

In [44]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr = np.arange(0, 10, step = 2)
arr

array([0, 2, 4, 6, 8])

In [46]:
np.linspace(1, 20, 50)


array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

In [47]:
## copy function and broadcasting
arr[3:] = 100

In [49]:
arr

array([  0,   2,   4, 100, 100])

In [50]:
arr1 = arr  ## array is also called refrence type

In [51]:
arr1 [3:] = 500
arr1

array([  0,   2,   4, 500, 500])

In [52]:
arr

array([  0,   2,   4, 500, 500])

In [54]:
arr2 = arr.copy()
arr2

array([  0,   2,   4, 500, 500])

In [55]:
print(arr)
arr1[3:] = 1000
print(arr1)

[  0   2   4 500 500]
[   0    2    4 1000 1000]


In [56]:
arr

array([  0,   2,   4, 500, 500])

In [57]:
## some condition very useful in  Exploratory data analysis
val = 2
arr<2

array([ True, False, False, False, False])

In [58]:
arr*2

array([   0,    4,    8, 1000, 1000])

In [59]:
arr/2

array([  0.,   1.,   2., 250., 250.])

In [60]:
arr[arr<300]

array([0, 2, 4])

In [61]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [62]:
np.zeros(6, dtype = int)

array([0, 0, 0, 0, 0, 0])

In [63]:
# random distribution
np.random.rand(3,3)

array([[0.53102864, 0.80674983, 0.26596984],
       [0.58736558, 0.37850243, 0.06111793],
       [0.54073386, 0.47737985, 0.19396768]])

In [64]:
arr_ex = np.random.randn(4,4)

In [65]:
arr_ex

array([[ 0.20814651,  0.9128879 ,  1.34564198, -0.78855243],
       [ 0.52578321,  0.94558804, -0.66035947,  1.34524179],
       [ 0.3236582 , -0.88428327, -0.03960608,  0.39809898],
       [-2.05594062,  1.89581822, -0.36951665,  0.51746746]])

In [66]:
import seaborn as sns
import pandas as pd

In [8]:
sns.distplot(pd.DataFrame(arr_ex.reshape(16,1)))

NameError: name 'sns' is not defined

In [ ]:
np.random.randint(0, 100, 8).reshape(2,4)

In [ ]:
np.random.random_sample((1,5))