# Numpy

NumPy is a fundamental library for scientific computing in Python. It provides supports for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on array and vectorized operations.

In [1]:
!pip install numpy

In [2]:
import numpy as np

In [8]:
## create array using numpy
## create a 1D array

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [20]:
## 2D array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)  # One row and 5 Columns.

array([[1, 2, 3, 4, 5]])

In [17]:
arr2 = np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [18]:
arr2= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(arr2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [22]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [27]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [30]:
# inbuilt function

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
## Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
## Attributes of Numpy Array
arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n", arr)
print("Shape:",arr.shape) # Output:(2,3)
print("Number of dimensions:", arr.ndim) # Output:2 
print("Size (number of elements:)", arr.size) # Output:6
print("Data type:",arr.dtype) # Output: int64(may vary based on platform)
print("Item size (in bytes):",arr.itemsize) #Output:8 (may vary based  on platform)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements:) 6
Data type: int32
Item size (in bytes): 4


In [40]:
## Numpy Vectorized Operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

### Element wise addition
print("Addition:", arr1+arr2)

### Element wise subtraction
print("Subtraction: ", arr1-arr2)

### Element wise Multiplication
print("Multiplication: ", arr1 * arr2)

### Element wise division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Subtraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [42]:
## Universal Function
arr = np.array([1,2,3,4,5,6])

## square root
print(np.sqrt(arr))

## Exponential 
print(np.exp(arr))

## sin
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


### Array slicing and Indexing

In [44]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n",arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [45]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
## Find the 1 number position
arr[0]

array([1, 2, 3, 4])

In [72]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [59]:
## 7,8,11,12  find

arr[1: ,2:]


array([[ 7,  8],
       [11, 12]])

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [76]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


### Modify the elements

In [83]:
## modify the 1 element to 100
arr [0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [85]:
arr
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


### Statistical concepts -- Normalization 
#### To have mean 0 and standard deviation 1

In [ ]:
data = np.array([1,2,3,4,5])

## Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data-mean) / std_dev
print("Normalized data:", normalized_data)

## Output : Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


#### Mean, Median, Mode

In [ ]:
data = np.array([1,2,3,4,5])

## Mean
mean = np.mean(data)
print(f"Mean: {mean}")

## Median
median = np.median(data)
print(f"Median: {median}")

## Standard Deviation
std_dev = np.std(data)
print(f"Standard Deviation: {std_dev}")

## Variance
variance = np.var(data)
print(f"Variance : {variance}")

Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951
Variance : 2.0


In [24]:
## Logical operation
data = np.array([1,2,3,4,5,6,7,8,9,10])

# data > 5 
data[(data>5) & (data<=8)]

array([6, 7, 8])